{% set name = "psyplot-gui" %}
{% set version = "1.2.0" %}
{% set sha256 = "130da0c8433a37b67bc50a19927ed94fc4472c29a86c0e2411cf2cf2818a548e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - psyplot
    - qtconsole
    - fasteners
    - sphinx
    - sphinx_rtd_theme

test:
  commands:
    - psyplot --help
  imports:
    - psyplot_gui
    - psyplot_gui.compat
    - psyplot_gui.config
    - psyplot_gui.sphinx_supp

app:
  entry: psyplot
  icon: logo.png
  summary: Psyplot visualization software
  type: desk

about:
  home: https://github.com/Chilipp/psyplot-gui
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: Graphical user interface for the psyplot package

  description: |
    This package provides a graphical user interface to interact with the
    psyplot framework.
  doc_url: http://psyplot.readthedocs.io/projects/psyplot-gui
  dev_url: https://github.com/Chilipp/psyplot-gui

extra:
  recipe-maintainers:
    - Chilipp
