travis:
  secure:
    BINSTAR_TOKEN: cIpSAtQe1uGOYO9qP0Rzbkg8ZDSDfJKSJybvQRFOgD4c8ZgfsAVgam1C5E/rjukeP/LLRRQ+mo4DPIKoyncFX5ngvFdNIkQPGcsX9OidaGEmhvumEn1SaoyYUS9J4/8ytdg+9ldJfAg33n6Z08RPehgVDopydtHYvJqsIxhYngoYKg073rHuEFGsKdAp4jpeebUNe91xEOwIh6szZVJhae4TFGAoL4p+FPbmGg7SwbIqNIwfPnjmAjIvP6bgR9oSzRcXoEGVvOTkJY0BbNEUGx8xdQY0wX6+wu3YBRqlY9Q8HPifj/ivfbLePpNfbOqch+ZCvb04qauiL03PWS/XiFwF7OLav+Sq2eLfq6987BxpBR3WBz9vc86MbuDOZ5xFyI3JnvB5NuX5zI/TFS7yUizxswJtJgzR/W315BJoAG7EY0xb+6eSTJx5TTIHggi+j9xAVz44zxV9D4SY7Pm78DIj/4vOgLnutXv4daK8QPl5gyeA+zFQRWMcw0Yjjf0sGEOkTrt9SagRS/kHHuGNLGrih78EHNE9bKt6seypa/qQlV4ovnlXS/ushYaQpCALmfJC0fRei8s1+GShNxZ71A8C/xSuUmud1lfbqjBaAy7nQEQJvgTUsRm64y0RNy/eEO34GWrFOdlSmQW3ASlz1azaeEHHxLd7hCpcBKjIEkI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
