travis:
  secure:
    BINSTAR_TOKEN: T3cGcdxsmKMG+ev/yhNB+wPRIDC7QcTqT88OYYkt3867DpU0RFMc1LNsFDUIjbS2bkEhhHk5M7bqyuf5IxImPvB2y/puygXvdIYj1vLfYDKTLqNeEeYRE2N8JWSbnoxCTWRhkSh6D+ZPdYdQBld27L/pjsdVzx9v86TJQRxZUkgiP/frEK2ndhQWAQDMPGa6cKPdwLfCm6jivG9KGnLUw4KHRo7rREgrLulMk1m0mgRDyF4glrDJ26Wbzd6pSWr0bAP160sJ8xWJcCLnzL6rl4hEmdd+liBByu12VtTg7SeRvi1R2qc50cvcMHQC+ZxZIrJiuMnta2Diz1ZQ9LqQ73VXH0/KV0oVmkx0FS3fwelEVUwcOBqrydDFoFlZI1vAyFKMnfSjy6J/BSwu3jZWqPHTpWQNhEHBtcANwWHR1DjMqLaMwyppTeH4Q1zuyvIc8NArgqdG6T6O/49DiYpS/Fdv9Dype3K6eVpuwfu+IKBstglxhsvpbXJiR7dG5eHW0RcwURFn7GK/sxm/K94Z2EN1N9JhFHC8qTSKIu9yW4kZ2mg7M99cMKkdP+q0LYL9JWvHIZbqIyEDvD0OJ+uaDh75S5Jl1ncS/P1/sKuqG2bvJN2f0Fx2tRg4mpR29vA/gmqYLbEUhKiCMo3U5h7lHaWvB9W3H7mcuA9LQNuT2aI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
