travis:
  secure:
    BINSTAR_TOKEN: v+luJNQVcf1d/yo5TcDGfBULEjCbHvQYnfCX5bejg5taL37SIHs4YxZmhaNSxrEA+950zp5wr91kLqNZ2517T77Ntq+CXcRSqC6pbtWBS671ZzhWb2kdMVTrcqFftxZW0Ukf6WnzuCP/pL2L14Sy8dDoojV/aYm5gqDl/lnXmRpmVEstNC80pkmDR+s2NB3dmeA3NBFAVqDfvhbz3r/0M4okQkhu0FaKwbBg7EaJAFq7NgvnJoQTpvE36zVlAte5U44Lh/lKs/KuOacp+ZVYp67xZPb+HhkvUsTJ+44HZoC4Mu5FS70wL4uPGn26HdP8qMvtTleAX/DtQG89oaloQ/YSvNlkoaaN6mj9zp/FCvxlHKoU67dAexuYRrNtR6cf6NxClgUMgUwMz//eh67Tvme9lKzZtEDkM9uWRixH6r6eA/P8daLzcynNQ7RKPZhPqFa0hNVSaJ8fCSusbXwITUE4IWQaTJMoiSj6KszJ2S06kQ/x1jvyLrFg5ke7+fqnCuHkrq0myrUY3krCiAO8QSm9FVcoBKVHSLrHjWWC/FtTzjBrHtvX/2hNQ3IaPvecGEyixQErqTzxM9hljtPyCI/4Xb7pQ1aiyplqOOgMMuTqgf0fb5UbcPKHtNHYvnGizR26u6KUMuzbkSVDbK2otZZCg1hUCdLMiPHrSm9s1Yg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
