travis:
  secure:
    BINSTAR_TOKEN: xteQKkxBd0+B0gEvF4IpTGK7455YZms3XYFe+RdSWCSEQTKRWFvKYQ6PnWOsIT6Np0+CROYk07Tk6aRb0h9j0n4sg9IQQgTdTJtebeaUFcV5/miZca+OGo5Nu6FBNdXPqly/osUV6dje1m3XjZV/XtAlFha9rO3jhVDX4nzTZpXQ7t/heO8ZkEvFj1wwkb0R7SaWRicjAUEZXhN5dEJ21Si3K8yZq73ZlQOOa8hKb2oGq/opjP8yi8VkXrGrR0rAcAfqZVQR6idlNfh+ih52XfRKl99dHQxXlkJGh4yCbeVopc7T0XFZbavxXU/yI2tK9vLZII0jwHfZusBSeKuFiNwX19i6ZBFOa/fcbj6pKf9xA/arChFdZzrJs7x5z7cJf1IoCL052Uq/g52LR5JpSi5R66DR7N9PU1JvQzVVOb0QS76j7UdzNg/l0M0rHOy5MtDRhE1a/7i5AiWPvrtTmrPwcbRiAtvcttWowK7vKB5xzKWUW6vTnhUUrey8ALk9sibJjaE6aavjFjT/8IpdZVrJLhRhrEH9sMK4luss2KDimKUyUa0FvHYda+vWh43SAqboIBQrWDSTBKdRxK3nfvVSQP0zYl6hOQKoQmyH0kY7+jqxRmcMzNPSuqK2x3iIwjZGoCIh3A2EozHuwgwGaOZQEwv2bNz1cRZNLgsXxS8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
