travis:
  secure:
    BINSTAR_TOKEN: qU6oaeHgbfBbyZb6h7izLNFgo0hqAAkvh3pKvkNGUtksl1IEQvXcVuA/NF88s4DWDI07LFKKRod2woWb17o7ijQL8DGCa71l6xbv+5aiw4NE+FG9utFZI1HjHQN+ZDhs1N7GNSMtxKxjox2q+DAtbKoInSmzGwvv3fsFJGKx2WLG8VBG8x9RrvGW53a8nvYioKMpkNyyPfQ0p4T6C+ONE/TwEpeWK1gRu0Uots0TLdetvHj9se525PXIUoQqOUD2GM/B4p734rCRdve/5yHnkM2uMcn8/d4HvrWcx248hjGzBdxTceksMuQqWOLJ2vUN4748TeRlI4Ey6F7e967taN5y2PfmYP24OfdlVs/9xCG/dixJyHaWKc2Lv4wGvrpa6xyDlprIeogid3XvieK72PXIi47kQVGOXaesbIoHMB/6MweUBGBS/H+QkettjqjSB3h6sArGTLxmDvUvCsJRsXROay8OpmWktbfz6Q5Eo58H61ihOVg1Jv6btSEfZ3evYb4v+7xGydj0p4ypnU6b3QvUVIkQz7W7yD0o5eHdqXLdlPAxomA+BNqyCtF4jG/WsnTdI0b7ewHr5jUezlHk0Bs8VgWSxnQOHw/hr0mtELybQMEuO/c7qX1G6UAd56dLgn/YlgVqa46DiNXBxWIH6hu4I2nH9KiAgWE1SoO/xVk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
